# ───────────────────────────────────────────────
#        ❤️ SWRewards by kapusta2039 ❤️
# funpay: https://funpay.com/users/2600949/
# ───────────────────────────────────────────────
options:
  lang: ru # Language -> Русский | en — English
  
  time_zone: "Europe/Moscow" # Часовой пояс -> Москва

  storage-method: H2 # Поддержка MySQL, H2, SQLite

  # Настройки подключения MySQL (Только для storage-method: MySQL)
  data:
    host: localhost
    port: 3306
    database: swrewards
    username: root
    password: ""
    pool-size: 10

  # Настройки AFK
  time_to_afk: "5m"
  afk:
    afk_actionbar: true # Оповещение об AFK в ActionBar
    afk_bossbar: true # Оповещение об AFK в BossBar
    afk_message: true # Оповещение об AFK в чат
