name: SWRewards
version: '${version}'
author: kapusta2039
website: https://github.com/kapusta2039
main: com.kapusta2039.swrewards.SWRewards
api-version: '1.21'
folia-supported: true
description: Настраиваемый плагин для вознаграждений за проведённое время на сервере

libraries:
  - com.h2database:h2:2.2.224
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.1.0
  - com.mysql:mysql-connector-j:8.3.0
  
commands:
  swrewards:
    description: Основная команда плагина
    aliases: [swreward, swr]
    usage: "/<command> reload"

permissions:
  swrewards.reload:
    description: Позволяет перезагрузить конфигурацию плагина
    default: op
  swrewards.admin:
    description: Все функции для администратора
    default: op
    children:
      swrewards.reload: true
